repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
        always_run: false
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: flake8
        exclude: (migrations)
# -   repo: https://github.com/thclark/pre-commit-sphinx
#     rev: 0.0.1
#     hooks:
#     -   id: build-docs
#         additional_dependencies: [sphinxcontrib-django]
#         args: ['--cache-dir', 'src/docs/build/doctrees', '--html-dir', 'src/docs/build/html', '--source-dir', 'src/docs/source']
#         language_version: python3
