version: '3.8'

services:

  db:
    image: mysql:latest
    container_name: signal_documentation-db
    restart: always
    env_file:
      - ./.env
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - mysql:/var/lib/mysql/
    ports:
      - "3306:3306"

  # Production service - "service", "image", and "container_name" should all contain the same
  # reference, based on the name of the service.
  sdwebapp:
    image: ${REGISTRY}signal_documentation-sdwebapp${TAG}
    build:
      context: .

    env_file:
      - ./.env
    container_name: signal_documentation-sdwebapp
    restart: on-failure
    command: sh -c "python3 /usr/src/signal_documentation/src/manage.py migrate --noinput &&
                    python3 /usr/src/signal_documentation/src/manage.py collectstatic --noinput &&
                    python3 /usr/src/signal_documentation/src/manage.py loaddata ./fixtures/* &&
                    python3 /usr/src/signal_documentation/src/manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/usr/src/signal_documentation
    ports:
      - "8000:8000"
    depends_on:
      - db

  redis:
    image: redis
    container_name: signal_documentation-redis
    restart: always
    ports:
      - "6379:6379"

  # Production service - "service", "image", and "container_name" should all contain the same
  # reference, based on the name of the service.
  sdnginx:
    image: ${REGISTRY}signal_documentation-sdnginx${TAG}
    build: ./nginx
    env_file:
      - ./.env
    container_name: signal_documentation-sdnginx
    restart: on-failure
    volumes:
      - ./src/staticfiles:/staticfiles
    ports:
      - "80:80"
    depends_on:
      - sdwebapp

volumes:
  mysql:
  sdwebapp:
  static:
