version: '3.8'

services:

  db:
    image: mysql:latest
    container_name: signal_documentation_db
    restart: always
    env_file:
      - ./.env
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - mysql:/var/lib/mysql/
    ports:
      - "3306:3306"

  signal_documentation_webapp:
    image: ${REGISTRY}signal_documentation_webapp${TAG}
    build: .
    env_file:
      - ./.env
    container_name: signal_documentation_webapp
    command: sh -c "python /usr/src/signal_documentation/src/manage.py migrate --noinput &&
                    python /usr/src/signal_documentation/src/manage.py collectstatic --noinput &&
                    python /usr/src/signal_documentation/src/manage.py loaddata ./fixtures/available_geography.json &&
                    python /usr/src/signal_documentation/src/manage.py loaddata ./fixtures/pathogens.json &&
                    python /usr/src/signal_documentation/src/manage.py loaddata ./fixtures/signal_types.json &&
                    python /usr/src/signal_documentation/src/manage.py loaddata ./fixtures/signal_categories.json &&
                    gunicorn signal_documentation.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - .:/usr/src/signal_documentation
    ports:
      - "8000:8000"
    depends_on:
      - db

  redis:
    image: redis
    container_name: signal_documentation_redis
    restart: always
    ports:
      - "6379:6379"

  nginx:
    image: ${REGISTRY}signal_documentation_nginx${TAG}
    build: ./nginx
    env_file:
      - ./.env
    container_name: signal_documentation_nginx
    restart: on-failure
    volumes:
      - ./src/staticfiles:/staticfiles
    ports:
      - "80:80"
    depends_on:
      - signal_documentation_webapp

volumes:
  mysql:
  webapp:
  static:
