version: '3.8'

services:

  db:
    image: postgres:latest
    container_name: signal_documentation-db
    restart: always
    env_file:
     - ./.env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: ${POSTGRES_HOST}
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  webapp:
    build: .
    env_file:
     - ./.env
    container_name: signal_documentation-web
    command: sh -c "python /usr/src/signal_documentation/src/manage.py migrate --noinput &&
                    python /usr/src/signal_documentation/src/manage.py collectstatic --noinput &&
                    python /usr/src/signal_documentation/src/manage.py loaddata .\fixtures\available_geography.json &&
                    python /usr/src/signal_documentation/src/manage.py loaddata .\fixtures\pathogens.json &&
                    python /usr/src/signal_documentation/src/manage.py loaddata .\fixtures\signal_types.json &&
                    python /usr/src/signal_documentation/src/manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/usr/src/signal_documentation
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  postgres:
  webapp:
