version: '3.8'

services:

  db:
    image: mysql:latest
    container_name: signal_documentation-db
    restart: always
    env_file:
      - ./.env
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - mysql:/var/lib/mysql/
    ports:
      - "3306:3306"

  sdwebapp:
    image: ${REGISTRY}signal_documentation-webapp${TAG}
    build:
      context: .

    env_file:
      - ./.env
    container_name: signal_documentation-webapp
    restart: on-failure
    command: sh -c "python3 /usr/src/signal_documentation/src/manage.py migrate --noinput &&
                    python3 /usr/src/signal_documentation/src/manage.py collectstatic --noinput &&
                    python3 /usr/src/signal_documentation/src/manage.py loaddata ./fixtures/available_geography.json &&
                    python3 /usr/src/signal_documentation/src/manage.py loaddata ./fixtures/pathogens.json &&
                    python3 /usr/src/signal_documentation/src/manage.py loaddata ./fixtures/signal_types.json &&
                    python3 /usr/src/signal_documentation/src/manage.py loaddata ./fixtures/signal_categories.json &&
                    python3 /usr/src/signal_documentation/src/manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/usr/src/signal_documentation
    ports:
      - "8000:8000"
    depends_on:
      - db

  redis:
    image: redis
    container_name: signal_documentation-redis
    restart: always
    ports:
      - "6379:6379"

  sdnginx:
    image: ${REGISTRY}signal_documentation-nginx${TAG}
    build: ./nginx
    env_file:
      - ./.env
    container_name: signal_documentation-nginx
    restart: on-failure
    volumes:
      - ./src/staticfiles:/staticfiles
    ports:
      - "80:80"
    depends_on:
      - sdwebapp

  celery:
    build: .
    env_file:
      - ./.env
    container_name: signal_documentation-celery
    working_dir: /usr/src/signal_documentation
    command: celery -A celery worker -l info
    volumes:
      - .:/usr/src/signal_documentation
    depends_on:
      - db
      - redis

  celery-beat:
    build: .
    env_file:
      - ./.env
    container_name: signal_documentation-celery-beat
    working_dir: /usr/src/signal_documentation
    command: celery -A celery beat -l info
    volumes:
      - .:/usr/src/signal_documentation
    depends_on:
      - db
      - redis

  flower:
    build: .
    env_file:
      - ./.env
    image: mher/flower
    container_name: signal_documentation-flower
    working_dir: /usr/src/signal_documentation
    command: celery -A celery flower -l info
    volumes:
      - .:/usr/src/signal_documentation
    ports:
      - "5555:5555"
    depends_on:
      - redis
      - celery
      - celery-beat

volumes:
  mysql:
  webapp:
  static:
  celery:
  celery-beat:
