version: '3.8'

services:

  db:
    image: mysql:latest
    container_name: signal_documentation-db
    restart: always
    env_file:
      - ./.env
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - mysql:/var/lib/mysql/
    ports:
      - "3306:3306"

  sdwebapp:
    image: ${REGISTRY}signal_documentation-webapp${TAG}
    build: .
    env_file:
      - ./.env
    container_name: signal_documentation-webapp
    restart: on-failure
    command: sh -c "python3 /usr/src/signal_documentation/src/manage.py migrate --noinput &&
                    python3 /usr/src/signal_documentation/src/manage.py collectstatic --noinput &&
                    python3 /usr/src/signal_documentation/src/manage.py loaddata ./fixtures/available_geography.json &&
                    python3 /usr/src/signal_documentation/src/manage.py loaddata ./fixtures/pathogens.json &&
                    python3 /usr/src/signal_documentation/src/manage.py loaddata ./fixtures/signal_types.json &&
                    python3 /usr/src/signal_documentation/src/manage.py loaddata ./fixtures/signal_categories.json &&
                    python3 /usr/src/signal_documentation/src/manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/usr/src/signal_documentation
    ports:
      - "8000:8000"
    depends_on:
      - db

  redis:
    image: redis
    container_name: signal_documentation-redis
    restart: always
    ports:
      - "6379:6379"

  sdnginx:
    image: ${REGISTRY}signal_documentation-nginx${TAG}
    build: ./nginx
    env_file:
      - ./.env
    container_name: signal_documentation-nginx
    restart: on-failure
    volumes:
      - ./src/staticfiles:/staticfiles
    ports:
      - "80:80"
    labels:
      - "autoheal=true"
    depends_on:
      - sdwebapp
    healthcheck:
      test: curl -f ghcr.io/cmu-delphi/signal_documentation-nginx || exit 1
      interval: 10s
      timeout: 10s
      start_period: 10s
      retries: 3

  autoheal:
    image: willfarrell/autoheal:latest
    tty: true
    restart: always
    environment:
      - AUTOHEAL_INTERVAL=60
      - AUTOHEAL_START_PERIOD=300
      - AUTOHEAL_DEFAULT_STOP_TIMEOUT=10
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  mysql:
  webapp:
  static:
