# Generated by Django 4.2 on 2023-05-04 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_type', models.CharField(choices=[('api_documentation', 'API Documentation'), ('dua', 'DUA'), ('other', 'Other')], help_text='Link type', max_length=128, unique=True)),
                ('url', models.URLField(help_text='Link url', max_length=256, unique=True)),
            ],
        ),
    ]
