# Generated by Django 4.2.1 on 2023-05-12 19:45

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactsConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(default='Address', max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ContactPhonenumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('contacts_config', models.ForeignKey(help_text='Contacts phone number', on_delete=django.db.models.deletion.CASCADE, related_name='phone_numbers', to='base.contactsconfiguration')),
            ],
        ),
        migrations.CreateModel(
            name='ContactLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name', max_length=128, unique=True)),
                ('url', models.URLField(help_text='Link url', max_length=256, unique=True)),
                ('contacts_config', models.ForeignKey(help_text='Contacts link', on_delete=django.db.models.deletion.CASCADE, related_name='links', to='base.contactsconfiguration')),
            ],
        ),
        migrations.CreateModel(
            name='ContactEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='Contact email', max_length=128)),
                ('contacts_config', models.ForeignKey(help_text='Contacts email', on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='base.contactsconfiguration')),
            ],
        ),
    ]
