# Generated by Django 4.2 on 2023-05-04 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='link_type',
            field=models.CharField(choices=[('api_documentation', 'API Documentation'), ('dua', 'DUA'), ('survey_details', 'SURVEY_DETAILS'), ('other', 'Other')], help_text='Link type', max_length=128, unique=True),
        ),
    ]
