# Generated by Django 4.2 on 2023-05-08 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_link_link_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='link_type',
            field=models.CharField(choices=[('api_documentation', 'API Documentation'), ('dua', 'DUA'), ('interpreting_mask', 'Interpreting mask use in context'), ('question_text', 'Question text'), ('survey_details', 'SURVEY_DETAILS'), ('survey_documentation', 'Survey documentation'), ('technical_description', 'Technical description'), ('wave_10_revision', 'Wave 10 revision updates'), ('wave_11_revision', 'Wave 11 revision updates'), ('other', 'Other')], help_text='Link type', max_length=128, unique=True),
        ),
    ]
