# Generated by Django 5.0.2 on 2024-02-29 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_link_created_link_modified'),
    ]

    operations = [
        migrations.CreateModel(
            name='DescriptedFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filter_name', models.CharField(choices=[('signals.filters.SignalFilter', 'signals.filters.SignalFilter')], max_length=256, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='link',
            name='link_type',
            field=models.CharField(choices=[('api_documentation', 'API Documentation'), ('dua', 'DUA'), ('interpreting_mask', 'Interpreting mask use in context'), ('question_text', 'Question text'), ('survey_details', 'Survey details'), ('survey_documentation', 'Survey documentation'), ('technical_description', 'Technical description'), ('wave_10_revision', 'Wave 10 revision updates'), ('wave_11_revision', 'Wave 11 revision updates'), ('other', 'Other'), ('example_url', 'Example URL')], help_text='Link type', max_length=128),
        ),
        migrations.CreateModel(
            name='DescriptedFilterField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filter_field', models.CharField(help_text='Filter field', max_length=256)),
                ('description', models.TextField(blank=True, help_text='Filter field description', null=True)),
                ('filter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filter_fields', to='base.descriptedfilter')),
            ],
            options={
                'unique_together': {('filter', 'filter_field')},
            },
        ),
    ]
