# Generated by Django 4.2.10 on 2024-06-07 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_descriptedfilter_alter_link_link_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='License', max_length=256, unique=True)),
                ('use_restrictions', models.TextField(blank=True, help_text='Use Restrictions', null=True)),
            ],
        ),
    ]
