# Generated by Django 4.2.3 on 2023-07-07 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signal',
            name='pathogen',
        ),
        migrations.AddField(
            model_name='signal',
            name='pathogen',
            field=models.ManyToManyField(help_text='Pathogen/Disease Area', related_name='signals', to='signals.pathogen'),
        ),
    ]
