# Generated by Django 4.2 on 2023-05-09 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signal',
            name='base',
            field=models.ForeignKey(help_text='Signal base', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='base_for', to='signals.signal'),
        ),
    ]
