# Generated by Django 4.2 on 2023-05-04 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datasources', '0001_initial'),
        ('signals', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='geography',
            options={'verbose_name_plural': 'geographies'},
        ),
        migrations.AlterField(
            model_name='signal',
            name='source',
            field=models.ForeignKey(help_text='Source Subdivision', on_delete=django.db.models.deletion.PROTECT, related_name='signals', to='datasources.sourcesubdivision'),
        ),
    ]
