# Generated by Django 4.2.2 on 2023-06-09 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0002_alter_signal_base'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='geography',
            options={'ordering': ['name'], 'verbose_name_plural': 'geographies'},
        ),
        migrations.AlterModelOptions(
            name='signaltype',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='signal',
            name='base',
            field=models.ForeignKey(blank=True, help_text='Signal base', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='base_for', to='signals.signal'),
        ),
    ]
