# Generated by Django 4.2.3 on 2023-07-19 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datasources', '0003_referencesignal_alter_datasource_description_and_more'),
        ('signals', '0002_remove_signal_pathogen_signal_pathogen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signal',
            name='description',
            field=models.TextField(blank=True, help_text='Description', max_length=1000),
        ),
        migrations.AlterField(
            model_name='signal',
            name='short_description',
            field=models.TextField(blank=True, help_text='Short Description', max_length=500),
        ),
        migrations.CreateModel(
            name='SignalGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name', max_length=128, unique=True)),
                ('subdivisions', models.ManyToManyField(help_text='Source Subdivisions', related_name='signal_groups', to='datasources.sourcesubdivision')),
            ],
        ),
        migrations.AlterField(
            model_name='signal',
            name='base',
            field=models.ForeignKey(help_text='Base', on_delete=django.db.models.deletion.PROTECT, related_name='signals', to='signals.signalgroup'),
        ),
    ]
