# Generated by Django 4.2.3 on 2023-07-14 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0002_remove_signal_pathogen_signal_pathogen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signal',
            name='base',
        ),
    ]
