# Generated by Django 4.2 on 2023-05-08 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0002_alter_geography_options_alter_signal_source'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signal',
            name='base_name',
        ),
        migrations.AddField(
            model_name='signal',
            name='base',
            field=models.ForeignKey(help_text='Signal base', null=True, on_delete=django.db.models.deletion.SET_NULL, to='signals.signal'),
        ),
        migrations.AlterField(
            model_name='signal',
            name='time_label',
            field=models.CharField(choices=[('day', 'Day'), ('week', 'Week')], help_text='Time label', max_length=128),
        ),
        migrations.DeleteModel(
            name='SignalBaseName',
        ),
    ]
