# Generated by Django 4.2.3 on 2023-07-31 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0002_alter_signal_options_geography_created_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='signal',
            options={'ordering': ['modified']},
        ),
    ]
