# Generated by Django 4.2.6 on 2023-11-01 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0003_alter_signal_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signal',
            old_name='format',
            new_name='format_type',
        ),
    ]
