# Generated by Django 4.2 on 2023-05-08 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0003_remove_signal_base_name_signal_base_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signal',
            name='signal_type',
        ),
        migrations.AddField(
            model_name='signal',
            name='signal_type',
            field=models.ManyToManyField(help_text='Signal Type', related_name='signals', to='signals.signaltype'),
        ),
    ]
