# Generated by Django 4.2.10 on 2024-02-15 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0004_rename_format_signal_format_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='signalcategory',
            options={'ordering': ['name'], 'verbose_name_plural': 'signal categories'},
        ),
        migrations.AddField(
            model_name='signal',
            name='from_date',
            field=models.DateField(blank=True, help_text='From Date', null=True),
        ),
        migrations.AddField(
            model_name='signal',
            name='last_updated',
            field=models.DateField(blank=True, help_text='Last Updated', null=True),
        ),
        migrations.AddField(
            model_name='signal',
            name='to_date',
            field=models.DateField(blank=True, help_text='To Date', null=True),
        ),
    ]
