# Generated by Django 5.0.2 on 2024-02-19 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0005_alter_signalcategory_options'),
        ('signals', '0005_alter_signalcategory_options_signal_from_date_and_more'),
    ]

    operations = [
    ]
