# Generated by Django 5.0.3 on 2024-05-02 12:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0006_merge_20240219_1508'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='signaltype',
            options={},
        ),
        migrations.CreateModel(
            name='GeographyUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('geo_id', models.CharField(help_text='Geo ID', max_length=128)),
                ('name', models.CharField(help_text='Name', max_length=128)),
                ('display_name', models.CharField(help_text='Display Name', max_length=128)),
                ('postal', models.CharField(help_text='Postal', max_length=128, null=True)),
                ('level', models.IntegerField(help_text='Level')),
                ('geography', models.ForeignKey(help_text='Geography', on_delete=django.db.models.deletion.CASCADE, related_name='geography_units', to='signals.geography')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
