# Generated by Django 5.0.3 on 2024-04-26 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0006_merge_20240219_1508'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemographicScope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Name', max_length=128, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GeographicScope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Name', max_length=128, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='signaltype',
            options={},
        ),
        migrations.AddField(
            model_name='signal',
            name='age_breakdown',
            field=models.CharField(choices=[('0-17', '0-17'), ('18-64', '18-64'), ('65+', '65+')], help_text='Age Breakdown', max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='signal',
            name='data_censoring',
            field=models.TextField(blank=True, help_text='Data Censoring', null=True),
        ),
        migrations.AddField(
            model_name='signal',
            name='gender_breakdown',
            field=models.BooleanField(default=False, help_text='Gender Breakdown'),
        ),
        migrations.AddField(
            model_name='signal',
            name='missingness',
            field=models.TextField(blank=True, help_text='Missingness', null=True),
        ),
        migrations.AddField(
            model_name='signal',
            name='race_breakdown',
            field=models.BooleanField(default=False, help_text='Race Breakdown'),
        ),
        migrations.AddField(
            model_name='signal',
            name='reporting_cadence',
            field=models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly')], help_text='Reporting Cadence', max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='signal',
            name='severenity_pyramid_rungs',
            field=models.CharField(choices=[('population', 'Population'), ('infected', 'Infected'), ('symptomatic', 'Symptomatic'), ('outpatient_visit', 'Outpatient visit'), ('ascertained', 'Ascertained (case)'), ('hospitalized', 'Hospitalized'), ('icu', 'ICU'), ('dead', 'Dead')], help_text='Severity Pyramid Rungs', max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='signal',
            name='demographic_scope',
            field=models.ManyToManyField(help_text='Demographic Scope', related_name='signals', to='signals.demographicscope'),
        ),
    ]
