# Generated by Django 4.2.10 on 2024-05-14 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0007_alter_signaltype_options_geographyunit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='geographyunit',
            name='postal',
        ),
    ]
