# Generated by Django 5.0.3 on 2024-06-06 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0008_remove_geographyunit_postal'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemographicScope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Name', max_length=128, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GeographicScope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Name', max_length=128, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Licence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Name', max_length=128, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('organisation_name', models.CharField(help_text='Organisation Name', max_length=128, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='signal',
            name='available_geography',
        ),
        migrations.AddField(
            model_name='signal',
            name='age_breakdown',
            field=models.CharField(choices=[('0-17', '0-17'), ('18-64', '18-64'), ('65+', '65+')], help_text='Age Breakdown', max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='signal',
            name='data_censoring',
            field=models.TextField(blank=True, help_text='Data Censoring', null=True),
        ),
        migrations.AddField(
            model_name='signal',
            name='gender_breakdown',
            field=models.BooleanField(default=False, help_text='Gender Breakdown'),
        ),
        migrations.AddField(
            model_name='signal',
            name='missingness',
            field=models.TextField(blank=True, help_text='Missingness', null=True),
        ),
        migrations.AddField(
            model_name='signal',
            name='race_breakdown',
            field=models.BooleanField(default=False, help_text='Race Breakdown'),
        ),
        migrations.AddField(
            model_name='signal',
            name='reporting_cadence',
            field=models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly')], help_text='Reporting Cadence', max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='signal',
            name='restrictions',
            field=models.TextField(blank=True, help_text='Restrictions', null=True),
        ),
        migrations.AddField(
            model_name='signal',
            name='severenity_pyramid_rungs',
            field=models.CharField(choices=[('population', 'Population'), ('infected', 'Infected'), ('symptomatic', 'Symptomatic'), ('outpatient_visit', 'Outpatient visit'), ('ascertained', 'Ascertained (case)'), ('hospitalized', 'Hospitalized'), ('icu', 'ICU'), ('dead', 'Dead')], help_text='Severity Pyramid Rungs', max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='signal',
            name='temporal_scope_end',
            field=models.DateField(blank=True, help_text='Temporal Scope End', null=True),
        ),
        migrations.AddField(
            model_name='signal',
            name='temporal_scope_end_note',
            field=models.TextField(blank=True, help_text='Temporal Scope End Note', null=True),
        ),
        migrations.AddField(
            model_name='signal',
            name='temporal_scope_start',
            field=models.DateField(blank=True, help_text='Temporal Scope Start', null=True),
        ),
        migrations.AddField(
            model_name='signal',
            name='temporal_scope_start_note',
            field=models.TextField(blank=True, help_text='Temporal Scope Start Note', null=True),
        ),
        migrations.AddField(
            model_name='signal',
            name='typical_reporting_lag',
            field=models.CharField(blank=True, help_text='Typical Reporting Lag', max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='signal',
            name='typical_revision_cadence',
            field=models.CharField(blank=True, help_text='Typical Revision Cadence', max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='signal',
            name='demographic_scope',
            field=models.ManyToManyField(help_text='Demographic Scope', related_name='signals', to='signals.demographicscope'),
        ),
        migrations.AddField(
            model_name='signal',
            name='geographic_scope',
            field=models.ManyToManyField(help_text='Geographic Scope', to='signals.geographicscope'),
        ),
        migrations.AddField(
            model_name='signal',
            name='licence',
            field=models.ManyToManyField(help_text='Licence', related_name='signals', to='signals.licence'),
        ),
        migrations.AddField(
            model_name='signal',
            name='organisations_access_list',
            field=models.ManyToManyField(help_text='Organisations Access List. Who may access this signal?', related_name='accessed_signals', to='signals.organisation'),
        ),
        migrations.AddField(
            model_name='signal',
            name='organisations_sharing_list',
            field=models.ManyToManyField(help_text='Organisations Sharing List. Who may be told about this signal?', related_name='shared_signals', to='signals.organisation'),
        ),
        migrations.CreateModel(
            name='GeographySignal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aggregated_by_delphi', models.BooleanField(default=False)),
                ('geography', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='signals.geography')),
                ('signal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='signals.signal')),
            ],
            options={
                'unique_together': {('geography', 'signal')},
            },
        ),
    ]
