# Generated by Django 5.0.3 on 2024-06-06 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0009_demographicscope_geographicscope_licence_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='signal',
            name='available_geography',
            field=models.ManyToManyField(help_text='Available geography', through='signals.GeographySignal', to='signals.geography'),
        ),
    ]
