# Generated by Django 5.0.3 on 2024-06-06 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0010_signal_available_geography'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geographysignal',
            name='geography',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='geography_signals', to='signals.geography'),
        ),
        migrations.AlterField(
            model_name='geographysignal',
            name='signal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='geography_signals', to='signals.signal'),
        ),
    ]
