# Generated by Django 4.2.10 on 2024-06-07 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_license'),
        ('signals', '0011_alter_geographysignal_geography_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signal',
            name='licence',
        ),
        migrations.AddField(
            model_name='signal',
            name='license',
            field=models.ForeignKey(help_text='License', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='signals', to='base.license'),
        ),
        migrations.DeleteModel(
            name='Licence',
        ),
    ]
