# Generated by Django 4.2.10 on 2024-06-07 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0013_remove_signal_signal_type_signal_signal_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signal',
            name='from_date',
        ),
        migrations.RemoveField(
            model_name='signal',
            name='to_date',
        ),
    ]
