# Generated by Django 4.2.10 on 2024-06-07 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0014_remove_signal_from_date_remove_signal_to_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='signal',
            name='from_date',
            field=models.DateField(blank=True, help_text='From Date', null=True),
        ),
        migrations.AddField(
            model_name='signal',
            name='to_date',
            field=models.DateField(blank=True, help_text='To Date', null=True),
        ),
        migrations.AlterField(
            model_name='signal',
            name='temporal_scope_end',
            field=models.CharField(blank=True, help_text='Temporal Scope End', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='signal',
            name='temporal_scope_start',
            field=models.CharField(blank=True, help_text='Temporal Scope Start', max_length=128, null=True),
        ),
    ]
