# Generated by Django 4.2.10 on 2024-06-10 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0015_signal_from_date_signal_to_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signal',
            name='geographic_scope',
        ),
        migrations.AddField(
            model_name='signal',
            name='geographic_scope',
            field=models.ForeignKey(help_text='Geographic Scope', null=True, on_delete=django.db.models.deletion.SET_NULL, to='signals.geographicscope'),
        ),
    ]
