# Generated by Django 4.2.10 on 2024-06-11 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0016_remove_signal_geographic_scope_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='geography',
            name='display_name',
            field=models.CharField(blank=True, help_text='Display Name', max_length=128, null=True),
        ),
    ]
