# Generated by Django 4.2.10 on 2024-06-11 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0017_geography_display_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='geography',
            name='order_id',
            field=models.IntegerField(blank=True, help_text='Order ID', null=True),
        ),
    ]
