# Generated by Django 4.2.10 on 2024-06-11 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0018_geography_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signal',
            name='severenity_pyramid_rungs',
            field=models.CharField(choices=[('population', 'Population'), ('infected', 'Infected'), ('symptomatic', 'Symptomatic'), ('outpatient_visit', 'Outpatient / ED'), ('ascertained', 'Ascertained (case)'), ('hospitalized', 'Hospitalized'), ('icu', 'ICU'), ('dead', 'Dead')], help_text='Severity Pyramid Rungs', max_length=128, null=True),
        ),
    ]
