# Generated by Django 4.2.10 on 2024-06-20 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0019_alter_signal_severenity_pyramid_rungs'),
    ]

    operations = [
        migrations.AddField(
            model_name='signal',
            name='signal_availability_days',
            field=models.IntegerField(blank=True, help_text='Number of days the signal is available for', null=True),
        ),
    ]
