# Generated by Django 5.0.6 on 2024-07-11 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0020_signal_signal_availability_days'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signal',
            old_name='severenity_pyramid_rungs',
            new_name='severity_pyramid_rungs',
        ),
        migrations.AlterField(
            model_name='signal',
            name='age_breakdown',
            field=models.CharField(blank=True, choices=[('0-17', '0-17'), ('18-64', '18-64'), ('65+', '65+')], help_text='Age Breakdown', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='signal',
            name='organisations_access_list',
            field=models.ManyToManyField(blank=True, help_text='Organisations Access List. Who may access this signal?', related_name='accessed_signals', to='signals.organisation'),
        ),
        migrations.AlterField(
            model_name='signal',
            name='organisations_sharing_list',
            field=models.ManyToManyField(blank=True, help_text='Organisations Sharing List. Who may be told about this signal?', related_name='shared_signals', to='signals.organisation'),
        ),
        migrations.AlterField(
            model_name='signal',
            name='time_label',
            field=models.CharField(choices=[('day', 'Day'), ('date', 'Date'), ('dseek', 'Week')], help_text='Time label', max_length=128),
        ),
    ]
