# Generated by Django 5.0.6 on 2024-07-18 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0021_rename_severenity_pyramid_rungs_signal_severity_pyramid_rungs_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signal',
            name='active',
            field=models.BooleanField(default=False, help_text='Ongoing'),
        ),
        migrations.AlterField(
            model_name='signal',
            name='severity_pyramid_rungs',
            field=models.CharField(choices=[('population', 'Population'), ('infected', 'Infected'), ('symptomatic', 'Symptomatic'), ('outpatient visit', 'Outpatient / ED'), ('ascertained (case)', 'Ascertained (case)'), ('hospitalized', 'Hospitalized'), ('icu', 'ICU'), ('dead', 'Dead')], help_text='Severity Pyramid Rungs', max_length=128, null=True),
        ),
    ]
