# Generated by Django 4.2 on 2023-05-04 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0002_alter_link_link_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='SourceSubdivision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name', max_length=128, unique=True)),
                ('display_name', models.CharField(help_text='Display Name', max_length=128, unique=True)),
                ('description', models.TextField(blank=True, help_text='Source description', max_length=1000, null=True)),
                ('db_source', models.CharField(help_text='DB Source', max_length=128, unique=True)),
                ('links', models.ManyToManyField(help_text='DataSource links', related_name='source_subdivisions', to='base.link')),
            ],
        ),
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name', max_length=128, unique=True)),
                ('display_name', models.CharField(help_text='Display Name', max_length=128, unique=True)),
                ('description', models.TextField(blank=True, help_text='Source description', max_length=1000, null=True)),
                ('source_license', models.CharField(help_text='License', max_length=128)),
                ('links', models.ManyToManyField(help_text='DataSource links', related_name='data_sources', to='base.link')),
                ('source_subdivision', models.ForeignKey(help_text='Source Subdivision', on_delete=django.db.models.deletion.PROTECT, related_name='data_sources', to='datasources.sourcesubdivision')),
            ],
        ),
    ]
