# Generated by Django 4.2.2 on 2023-07-03 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datasources', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sourcesubdivision',
            name='db_source',
            field=models.CharField(help_text='DB Source', max_length=128),
        ),
    ]
