# Generated by Django 4.2 on 2023-05-08 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_link_link_type'),
        ('datasources', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datasource',
            name='source_subdivision',
        ),
        migrations.AddField(
            model_name='sourcesubdivision',
            name='data_source',
            field=models.ForeignKey(help_text='Source Subdivision', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_subdivisions', to='datasources.datasource'),
        ),
        migrations.AlterField(
            model_name='sourcesubdivision',
            name='links',
            field=models.ManyToManyField(help_text='Source Subdivision links', related_name='source_subdivisions', to='base.link'),
        ),
    ]
