# Generated by Django 4.2.3 on 2023-07-19 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datasources', '0002_alter_sourcesubdivision_db_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferenceSignal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name', max_length=128, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='datasource',
            name='description',
            field=models.TextField(blank=True, help_text='Source description', max_length=1000),
        ),
        migrations.AlterField(
            model_name='sourcesubdivision',
            name='description',
            field=models.TextField(blank=True, help_text='Source description', max_length=1000),
        ),
        migrations.AddField(
            model_name='sourcesubdivision',
            name='reference_signal',
            field=models.ForeignKey(help_text='Reference Signal', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='source_subdivisions', to='datasources.referencesignal'),
        ),
    ]
