# Generated by Django 4.2 on 2023-04-25 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datasources', '0002_geography_remove_signal_available_geography_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasource',
            name='signal_type',
            field=models.ForeignKey(help_text='Signal Type', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='data_sources', to='datasources.signaltype'),
        ),
    ]
