# Generated by Django 4.2.3 on 2023-07-31 17:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datasources', '0002_alter_sourcesubdivision_db_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasource',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2023, 7, 31, 17, 44, 34, 344934, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='datasource',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='sourcesubdivision',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2023, 7, 31, 17, 44, 38, 5382, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sourcesubdivision',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
