# Generated by Django 4.2.3 on 2023-07-21 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0004_remove_signal_base_signal_group_signalgroup_base'),
        ('datasources', '0003_referencesignal_alter_datasource_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sourcesubdivision',
            name='reference_signal',
            field=models.ForeignKey(help_text='Reference Signal', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subdivision_reference', to='signals.signal'),
        ),
    ]
