# Generated by Django 4.2 on 2023-04-26 10:51

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datasources', '0003_datasource_signal_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datasource',
            name='pathogen',
        ),
        migrations.RemoveField(
            model_name='signal',
            name='base_is_other',
        ),
        migrations.RemoveField(
            model_name='signal',
            name='compute_from_base',
        ),
        migrations.RemoveField(
            model_name='signal',
            name='link',
        ),
        migrations.AddField(
            model_name='signal',
            name='has_sample_size',
            field=models.BooleanField(default=False, help_text='Has Sample Size'),
        ),
        migrations.AddField(
            model_name='signal',
            name='has_stderr',
            field=models.BooleanField(default=False, help_text='Has StdErr'),
        ),
        migrations.AddField(
            model_name='signal',
            name='is_cumulative',
            field=models.BooleanField(default=False, help_text='Is Cumulative'),
        ),
        migrations.AddField(
            model_name='signal',
            name='is_smoothed',
            field=models.BooleanField(default=False, help_text='Is Smoothed'),
        ),
        migrations.AddField(
            model_name='signal',
            name='is_weighted',
            field=models.BooleanField(default=False, help_text='Is Weighted'),
        ),
        migrations.AddField(
            model_name='signal',
            name='links',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.URLField(max_length=256), blank=True, default=[], help_text='Links', size=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='signal',
            name='pathogen',
            field=models.ForeignKey(help_text='Pathogen/Disease Area', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pathogen', to='datasources.pathogen'),
        ),
        migrations.AlterField(
            model_name='signal',
            name='category',
            field=models.CharField(choices=[('public', 'Public'), ('early', 'Early'), ('cases_testing', 'Case testing'), ('late', 'Late'), ('other', 'Other')], help_text='Category', max_length=128),
        ),
    ]
