# Generated by Django 4.2 on 2023-04-28 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datasources', '0004_remove_datasource_pathogen_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_type', models.CharField(choices=[('api_documentation', 'API Documentation'), ('dua', 'DUA'), ('other', 'other')], help_text='Link type', max_length=128, unique=True)),
                ('url', models.URLField(help_text='Link url', max_length=256, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SignalBaseName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name', max_length=128, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='datasource',
            name='dua',
        ),
        migrations.RemoveField(
            model_name='datasource',
            name='signal_type',
        ),
        migrations.AddField(
            model_name='signal',
            name='signal_type',
            field=models.ForeignKey(help_text='Signal Type', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signal', to='datasources.signaltype'),
        ),
        migrations.RemoveField(
            model_name='signal',
            name='links',
        ),
        migrations.AddField(
            model_name='datasource',
            name='links',
            field=models.ManyToManyField(help_text='DataSource links', related_name='datasources', to='datasources.link'),
        ),
        migrations.AlterField(
            model_name='signal',
            name='base_name',
            field=models.ForeignKey(help_text='Signal BaseName', on_delete=django.db.models.deletion.PROTECT, to='datasources.signalbasename'),
        ),
        migrations.AddField(
            model_name='signal',
            name='links',
            field=models.ManyToManyField(help_text='Signal links', related_name='signals', to='datasources.link'),
        ),
    ]
