# Generated by Django 5.0.3 on 2024-06-05 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datasources', '0004_alter_datasource_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sourcesubdivision',
            name='external_name',
            field=models.CharField(help_text='External Name', max_length=128, null=True),
        ),
    ]
