# Generated by Django 4.2.10 on 2024-06-07 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_license'),
        ('datasources', '0005_sourcesubdivision_external_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasource',
            name='source_license',
            field=models.ForeignKey(help_text='License', on_delete=django.db.models.deletion.PROTECT, related_name='source_license', to='base.license'),
        ),
    ]
