# Generated by Django 4.2.10 on 2024-06-07 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_license'),
        ('datasources', '0006_alter_datasource_source_license'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasource',
            name='source_license',
            field=models.ForeignKey(help_text='License', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='data_sources', to='base.license'),
        ),
    ]
