name: Sync GitHub issues to Jira
on: [issues]

jobs:
  sync-issues:
    name: Sync issues to Jira
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/sync_with_jira/
        with:
          webhook-url: ${{ secrets.JIRA_WEBHOOK }}