name: Django Tests
on: [pull_request, push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Setup virtual environment
        run: |
          python3 -m pip install --upgrade pip
          sudo apt-get update -y
          sudo apt-get install graphviz graphviz-dev -y
          pip install pygraphviz
          pip install pipenv
          pipenv requirements > requirements.txt
          pip install -r requirements.txt

      - name: Run linters
        run: |
          pip install flake8
          flake8 .

      - name: Run tests
        run: python3 ./src/manage.py test
